name: flutter_user_guidance
description: An example of user guidance in Flutter.
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.11
  just_audio_windows: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/congratulations.mp3
